services:
  flirthub-app:
    container_name: flirthub-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Map external port 3001 to container's port 3000
    environment:
      - NODE_ENV=production
    restart: always
