services:
  ownerlist-app:
    container_name: ownerlist-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"  # Map external port 3001 to container's port 3000
    environment:
      - NODE_ENV=production
    restart: always
